-- Auto-generated by scripts/backfill-product-images.mjs
-- Backfills products.image_url for ~30 species whose seed row had an
-- empty imageUrl, by reusing a random image from the same category.
-- Idempotent: only updates rows that are still empty.

BEGIN;

UPDATE products SET image_url = 'https://297820.selcdn.ru/crm1/images/species/672.jpg?=2023-12-01+08%3A12%3A39' WHERE slug = 'mayras-white-multicolor-4354' AND (image_url IS NULL OR image_url = '');
UPDATE products SET image_url = 'https://297820.selcdn.ru/crm1/images/species/1616.jpg?=2023-12-01+06%3A28%3A36' WHERE slug = 'blue-multicolor-4917' AND (image_url IS NULL OR image_url = '');
UPDATE products SET image_url = 'https://297820.selcdn.ru/crm1/images/species/3629.jpg?=2023-12-01+06%3A28%3A38' WHERE slug = 'pink-foyd-multicolor-9016' AND (image_url IS NULL OR image_url = '');
UPDATE products SET image_url = 'https://297820.selcdn.ru/crm1/images/species/867.jpg?=2023-12-01+06%3A28%3A36' WHERE slug = 'la-belle-green-22503' AND (image_url IS NULL OR image_url = '');
UPDATE products SET image_url = 'https://297820.selcdn.ru/crm1/images/species/29206.jpg?=2023-12-01+06%3A28%3A51' WHERE slug = 'blue-jumbo-blue-26681' AND (image_url IS NULL OR image_url = '');
UPDATE products SET image_url = 'https://297820.selcdn.ru/crm1/images/species/28204.jpg?=2023-12-01+06%3A28%3A50' WHERE slug = 'show-flow-multicolor-27107' AND (image_url IS NULL OR image_url = '');
UPDATE products SET image_url = 'https://297820.selcdn.ru/crm1/images/species/18341.jpg?=2023-12-01+06%3A28%3A42' WHERE slug = 'yellow-yellow-27983' AND (image_url IS NULL OR image_url = '');
UPDATE products SET image_url = 'https://297820.selcdn.ru/crm1/images/species/22999.jpg?=2023-12-01+06%3A28%3A46' WHERE slug = 'mix-moon-purple-30712' AND (image_url IS NULL OR image_url = '');
UPDATE products SET image_url = 'https://297820.selcdn.ru/crm1/images/species/25232.jpg?=2023-12-01+06%3A28%3A48' WHERE slug = 'country-blues-multicolor-30894' AND (image_url IS NULL OR image_url = '');
UPDATE products SET image_url = 'https://297820.selcdn.ru/crm1/images/species/2417.jpg?=2023-12-01+06%3A28%3A37' WHERE slug = 'level-up-multicolor-31050' AND (image_url IS NULL OR image_url = '');
UPDATE products SET image_url = 'https://297820.selcdn.ru/crm1/images/species/27156.jpg?=2023-12-01+06%3A28%3A50' WHERE slug = 'daphne-multicolor-31776' AND (image_url IS NULL OR image_url = '');
UPDATE products SET image_url = 'https://297820.selcdn.ru/crm1/images/species/27156.jpg?=2023-12-01+06%3A28%3A50' WHERE slug = 'gelatto-multicolor-31777' AND (image_url IS NULL OR image_url = '');
UPDATE products SET image_url = 'https://297820.selcdn.ru/crm1/images/species/27156.jpg?=2023-12-01+06%3A28%3A50' WHERE slug = 'julieta-pretty-pink-multicolor-31778' AND (image_url IS NULL OR image_url = '');
UPDATE products SET image_url = 'https://297820.selcdn.ru/crm1/images/species/27156.jpg?=2023-12-01+06%3A28%3A50' WHERE slug = 'calinou-multicolor-31785' AND (image_url IS NULL OR image_url = '');
UPDATE products SET image_url = 'https://297820.selcdn.ru/crm1/images/species/29690.jpg?=2023-12-01+06%3A28%3A52' WHERE slug = 'big-pink-multicolor-31864' AND (image_url IS NULL OR image_url = '');
UPDATE products SET image_url = 'https://297820.selcdn.ru/crm1/images/species/27216.jpg?=2023-12-01+06%3A28%3A50' WHERE slug = 'la-mandarina-multicolor-31927' AND (image_url IS NULL OR image_url = '');
UPDATE products SET image_url = 'https://297820.selcdn.ru/crm1/images/species/3105.jpg?=2023-12-01+06%3A28%3A38' WHERE slug = 'moon-walk-multicolor-32007' AND (image_url IS NULL OR image_url = '');
UPDATE products SET image_url = 'https://297820.selcdn.ru/crm1/images/species/27672.jpg?=2023-12-01+06%3A28%3A50' WHERE slug = 'imagine-multicolor-32042' AND (image_url IS NULL OR image_url = '');
UPDATE products SET image_url = 'https://297820.selcdn.ru/crm1/images/species/28194.jpg?=2023-12-01+06%3A28%3A50' WHERE slug = 'darlene-multicolor-32186' AND (image_url IS NULL OR image_url = '');
UPDATE products SET image_url = 'https://297820.selcdn.ru/crm1/images/species/28194.jpg?=2023-12-01+06%3A28%3A50' WHERE slug = 'dima-bombastic-multicolor-32187' AND (image_url IS NULL OR image_url = '');
UPDATE products SET image_url = 'https://297820.selcdn.ru/crm1/images/species/28198.jpg?=2023-12-01+06%3A28%3A50' WHERE slug = 'white-ohara-white-32210' AND (image_url IS NULL OR image_url = '');
UPDATE products SET image_url = 'https://297820.selcdn.ru/crm1/images/species/28198.jpg?=2023-12-01+06%3A28%3A50' WHERE slug = 'pink-ohara-pink-32211' AND (image_url IS NULL OR image_url = '');
UPDATE products SET image_url = 'https://297820.selcdn.ru/crm1/images/species/4293.jpg?=2023-12-01+06%3A28%3A39' WHERE slug = 'superstition-multicolor-32535' AND (image_url IS NULL OR image_url = '');
UPDATE products SET image_url = 'https://297820.selcdn.ru/crm1/images/species/31870.jpg?=2024-05-27+14%3A26%3A08' WHERE slug = 'candy-dark-pink-32954' AND (image_url IS NULL OR image_url = '');
UPDATE products SET image_url = 'https://297820.selcdn.ru/crm1/images/species/27808.jpg?=2023-12-01+06%3A28%3A50' WHERE slug = 'scotland-5-light-pink-33191' AND (image_url IS NULL OR image_url = '');
UPDATE products SET image_url = 'https://297820.selcdn.ru/crm1/images/species/1912.jpg?=2023-12-01+06%3A28%3A37' WHERE slug = 'eye-wink-multicolor-33413' AND (image_url IS NULL OR image_url = '');
UPDATE products SET image_url = 'https://297820.selcdn.ru/crm1/images/species/25794.jpg?=2023-12-01+06%3A28%3A48' WHERE slug = 'large-multicolor-33441' AND (image_url IS NULL OR image_url = '');
UPDATE products SET image_url = 'https://297820.selcdn.ru/crm1/images/species/26990.jpg?=2023-12-01+06%3A28%3A49' WHERE slug = 'milky-way-multicolor-33459' AND (image_url IS NULL OR image_url = '');
UPDATE products SET image_url = 'https://297820.selcdn.ru/crm1/images/species/2588.jpg?=2023-12-01+06%3A28%3A37' WHERE slug = 'mix-white-pink-multicolor-33476' AND (image_url IS NULL OR image_url = '');
UPDATE products SET image_url = 'https://297820.selcdn.ru/crm1/images/species/2744.jpg?=2023-12-01+06%3A28%3A37' WHERE slug = 'moon-walk-5-multicolor-34108' AND (image_url IS NULL OR image_url = '');

COMMIT;
