'use client';
import MotionText from '@/components/motion-text';

import Link from 'next/link';
import {ArrowUpRight,Trash,ShoppingBag} from '@phosphor-icons/react';
import {listings,itemPrice,money,available} from '@/lib/catalog';
import {useShop} from './shop-context';
import {Quantity} from './products';
export default function CartView(){const s=useShop();const lines=s.cart.map(l=>({...l,p:listings.find(p=>p.id===l.id)!})).filter(l=>l.p);const subtotal=Math.round(lines.reduce((sum,l)=>sum+itemPrice(l.p,l.segment,s.currency)*l.quantity,0)*100)/100;
 if(!s.ready)return <main className="page-shell"><MotionText as="p">{s.t('Загружаем корзину…','Loading your cart…')}</MotionText></main>;
 if(!lines.length)return <main className="page-shell empty-state"><ShoppingBag size={52} weight="thin"/><span className="script">{s.t('Начнём с прекрасного','A beautiful beginning')}</span><MotionText as="h1">{s.t('Ваша корзина пока пуста','Your cart is waiting')}</MotionText><MotionText as="p">{s.t('Каждое чувство начинается с первого цветка.','Every feeling starts with a flower.')}</MotionText><Link href="/catalog" className="button primary">{s.t('Выбрать цветы','Choose flowers')}<ArrowUpRight size={21}/></Link></main>;
 return <main className="page-shell cart-page"><div className="page-heading"><MotionText as="h1">{s.t('Ваша','Your')} <span className="script">{s.t('корзина','selection')}</span></MotionText><Link href="/catalog" className="text-link">{s.t('Продолжить выбор','Keep exploring')}<ArrowUpRight size={18}/></Link></div><div className="cart-layout"><div><div className="cart-items">{lines.map(l=><article className="cart-item" key={l.id+l.segment}><Link href={'/products/'+l.p.product.slug+'?listing='+l.id}><img src={l.p.image} alt={l.p.product.name} width="160" height="200"/></Link><div className="cart-item-copy"><span className="eyebrow">{l.p.seller.name}</span><Link href={'/products/'+l.p.product.slug+'?listing='+l.id}><MotionText as="h3">{l.p.product.name}</MotionText></Link><MotionText as="p">{l.segment==='b2b'?s.t(`Коробка · ${l.p.box_quantity} стеблей`,`Box · ${l.p.box_quantity} stems`):s.t('За стебель','Per stem')} · {money(itemPrice(l.p,l.segment,s.currency),s.currency)}</MotionText><Quantity value={l.quantity} max={available(l.p,l.segment)} onChange={n=>s.update(l.id,l.segment,n)}/></div><div className="cart-item-price"><strong>{money(itemPrice(l.p,l.segment,s.currency)*l.quantity,s.currency)}</strong><button className="icon-button" onClick={()=>s.update(l.id,l.segment,0)} aria-label={s.t('Удалить ','Remove ')+l.p.product.name}><Trash size={20}/></button></div></article>)}</div><div className="checkout-login"><Link className="button primary" href="/checkout">{s.t('Перейти к оформлению','Continue to checkout')}</Link><p className="form-note">{s.t('Следующий шаг — получатель, доставка и демонстрация оплаты.','Next: recipient, delivery and payment preview.')}</p></div></div><aside className="order-summary"><MotionText as="h2">{s.t('Всё','Coming')} <span className="script">{s.t('сложилось','together')}</span></MotionText><div><span>{s.t('Цветы','Flowers')} ({lines.length})</span><span>{money(subtotal,s.currency)}</span></div><div><span>{s.t('Доставка, от','Delivery, from')}</span><span>{s.t('На следующем шаге','At checkout')}</span></div><div className="order-total"><span>{s.t('Итого, от','Estimated total')}</span><strong>{money(subtotal,s.currency)}</strong></div><MotionText as="p">{s.t('Предварительная стоимость. Окончательный расчёт — после подтверждения наличия и доставки.','Estimated price. Final total follows availability and delivery confirmation.')}</MotionText><Link className="text-link" href="/delivery">{s.t('Как мы доставляем','How delivery works')}<ArrowUpRight size={18}/></Link><div className="payment-marks"><span>МИР</span><span>СБП</span></div></aside></div></main>
}
