'use client';
import FlowerPhoto from './flower-photo';
import MotionText from '@/components/motion-text';

import Link from 'next/link';
import {useRef,useEffect,useState,type CSSProperties} from 'react';
import imageFraming from '@/data/image-framing.json';
const stemFrames:Record<string,{bottom:number;width:number;height:number}>=imageFraming;
import {Plus,ArrowUpRight,X,Check,Minus,ArrowRight,Heart} from '@phosphor-icons/react';
import {listings,type Listing,money,convert,unitPrice,itemPrice,categoryOf,available} from '@/lib/catalog';
import {useShop} from './shop-context';
export function Notice({closeModal}:{closeModal?:()=>void}){const s=useShop();if(!s.notice)return null;return <div className="cart-notice" role="status" aria-live="polite"><Check size={22}/><div><strong>{s.notice}</strong><span>{s.t('Добавлено в корзину','Added to your cart')}</span></div><Link href="/cart" onClick={()=>{s.setNotice('');closeModal?.()}}>{s.t('Перейти в корзину','Go to cart')} <ArrowRight size={18}/></Link><button aria-label={s.t('Закрыть уведомление','Close notification')} onClick={()=>s.setNotice('')}><X size={20}/></button></div>}
export function BuyButton({p,n=1,onNavigate}:{p:Listing;n?:number;onNavigate?:()=>void}){const s=useShop();return s.has(p.id)?<Link className="button primary in-cart" href="/cart" onClick={onNavigate}>{s.t('Перейти в корзину','Go to cart')}<ArrowRight size={20}/></Link>:<button className="button primary" disabled={!s.ready||!available(p,s.segment)} onClick={()=>s.add(p,n)}>{available(p,s.segment)?s.t('В корзину','Add to cart'):s.t('Нет в наличии','Sold out')}<Plus size={20}/></button>}
export function ProductCard({p,onQuick,index=0}:{p:Listing;onQuick:(p:Listing)=>void;index?:number}){const s=useShop();const frame=stemFrames[p.image];return <article className="product-card"><div className={"product-photo"+(frame?" product-photo--stem":"")} style={frame?{'--stem-offset':frame.bottom+'%'} as CSSProperties:undefined}><Link href={'/products/'+p.product.slug+'?listing='+p.id} aria-label={s.t('Открыть ','View ')+p.product.name}><FlowerPhoto sizes="(max-width: 700px) 50vw, (max-width: 1100px) 33vw, 30vw" src={p.image} alt={p.product.name} loading="lazy" width={frame?.width||600} height={frame?.height||720}/></Link><div className="photo-top"><span>{s.segment==='b2b'?s.t('Оптом','Wholesale'):categoryOf(p,s.en)}</span><span>{p.seller.country}</span></div><button className="quick-trigger" onClick={()=>onQuick(p)} aria-label={s.t('Быстрый просмотр ','Quick view ')+p.product.name}>{s.t('Рассмотреть','Take a closer look')}<ArrowUpRight size={18}/></button></div><div className="product-meta"><span>{p.seller.name}{p.stem_length_cm?' · '+p.stem_length_cm+' '+s.t('см','cm'):''}</span><span>0{index+1}</span></div><Link className="product-title" href={'/products/'+p.product.slug+'?listing='+p.id}>{p.product.name}<ArrowUpRight size={20}/></Link><div className="product-bottom"><div className="price">{money(unitPrice(p,s.segment,s.currency),s.currency)}<small> / {s.t('стебель','stem')}</small>{s.segment==='b2b'&&<span>{p.box_quantity} {s.t('шт. в коробке','stems per box')} · {money(itemPrice(p,s.segment,s.currency),s.currency)}</span>}{s.segment==='b2b'&&p.wholesale?.ams_price&&<span>AMS · {money(convert(Number(p.wholesale.ams_price),'RUB',s.currency),s.currency)} / {s.t('стебель','stem')}</span>}<span>{s.t('В наличии','Available')}: {available(p,s.segment).toLocaleString(s.en?'en-GB':'ru-RU')} {s.segment==='b2b'?s.t('кор.','boxes'):s.t('стеблей','stems')}</span></div><BuyButton p={p}/></div></article>}
export function Quantity({value,max,onChange}:{value:number;max:number;onChange:(n:number)=>void}){const s=useShop();return <div className="quantity"><button aria-label={s.t('Уменьшить количество','Decrease quantity')} disabled={value<=1} onClick={()=>onChange(value-1)}><Minus size={15}/></button><input aria-label={s.t('Количество','Quantity')} type="number" min="1" max={max} value={value} onChange={e=>{const n=Number(e.target.value);if(Number.isInteger(n)&&n>=1&&n<=max)onChange(n)}}/><button aria-label={s.t('Увеличить количество','Increase quantity')} disabled={value>=max} onClick={()=>onChange(value+1)}><Plus size={15}/></button></div>}
export function ProductDetail({p,closeModal,compact=false}:{p:Listing;closeModal?:()=>void;compact?:boolean}){const s=useShop();const[n,setN]=useState(1);useEffect(()=>setN(1),[p.id,s.segment]);return <div className={'product-detail '+(compact?'compact':'')}><div className="detail-image"><FlowerPhoto src={p.image} alt={p.product.name} width="800" height="900"/><span>{categoryOf(p,s.en)} / {p.seller.country}</span></div><div className="detail-copy"><span className="eyebrow">{p.seller.name} — {s.t('ОТ ПЛАНТАЦИИ','FROM THE GROWER')}</span><MotionText as="h1">{p.product.name}</MotionText><MotionText as="p">{s.en?(p.description_en||p.product.description):p.product.description}</MotionText><dl><div><dt>{s.t('Категория','Category')}</dt><dd>{categoryOf(p,s.en)}</dd></div>{p.stem_length_cm&&<div><dt>{s.t('Длина стебля','Stem length')}</dt><dd>{p.stem_length_cm} {s.t('см','cm')}</dd></div>}<div><dt>{s.t('Страна','Country')}</dt><dd>{p.seller.country==='EC'?s.t('Эквадор','Ecuador'):p.seller.country==='CO'?s.t('Колумбия','Colombia'):p.seller.country==='NL'?s.t('Нидерланды','Netherlands'):p.seller.country}</dd></div><div><dt>{s.t('Формат заказа','Order unit')}</dt><dd>{s.segment==='b2b'?s.t(`Коробка · ${p.box_quantity} стеблей`,`Box · ${p.box_quantity} stems`):s.t('Поштучно','Per stem')}</dd></div></dl><div className="detail-price">{money(unitPrice(p,s.segment,s.currency),s.currency)}<small> / {s.t('стебель','stem')}</small></div>{s.segment==='b2b'&&<MotionText as="p" className="muted">{s.t('За коробку','Per box')}: {money(itemPrice(p,s.segment,s.currency),s.currency)}{p.wholesale?.ams_price&&<span> · AMS {money(convert(Number(p.wholesale.ams_price),'RUB',s.currency),s.currency)} / {s.t('стебель','stem')}</span>}</MotionText>}<div className="buy-row">{!s.has(p.id)&&<Quantity value={n} max={available(p,s.segment)} onChange={setN}/>}<BuyButton p={p} n={n} onNavigate={closeModal}/></div><MotionText as="p" className="detail-total">{s.t('Итого','Total')}: {money(itemPrice(p,s.segment,s.currency)*n,s.currency)}</MotionText><div className="detail-delivery"><span>{s.t('Бережно доставим в ваш город','Carefully delivered to your city')}</span><Link href="/delivery" onClick={closeModal}>{s.t('Условия доставки','Delivery details')} ↗</Link></div><div className="payment-marks"><span>МИР</span><span>СБП</span><small>{s.t('Стоимость и наличие уточняются перед оплатой','Availability and total are confirmed before payment')}</small></div>{compact&&<Link className="text-link" href={'/products/'+p.product.slug+'?listing='+p.id} onClick={closeModal}>{s.t('Подробнее о цветке','View flower details')}<ArrowUpRight size={18}/></Link>}</div></div>}
export function QuickView({product,onClose}:{product:Listing|null;onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null);const s=useShop();useEffect(()=>{if(product){ref.current?.showModal();document.body.style.overflow='hidden'}else{ref.current?.close();document.body.style.overflow=''}return()=>{document.body.style.overflow=''}},[product]);return <dialog className="quick-dialog" ref={ref} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose()}} aria-label={s.t('Быстрый просмотр товара','Product quick view')}><button className="dialog-close icon-button" onClick={onClose} aria-label={s.t('Закрыть быстрый просмотр','Close quick view')}><X size={24}/></button><div className="dialog-scroll">{product&&<ProductDetail key={product.id} p={product} compact closeModal={onClose}/>}</div><Notice closeModal={onClose}/></dialog>}

export function SellerOffers({p}:{p:Listing}){const s=useShop();const offers=listings.filter(x=>x.product.id===p.product.id&&(s.segment!=='b2b'||x.wholesale));return <section className="seller-offers section"><div className="section-heading"><MotionText as="h2">{s.t('Предложения','Offers')} <span className="script">{s.t('плантаций','from growers')}</span></MotionText><span>{offers.length} {s.t('предложений','offers')}</span></div><div className="seller-offer-list">{offers.map(offer=><SellerOffer key={offer.id} p={offer}/>)}</div></section>}
function SellerOffer({p}:{p:Listing}){const s=useShop();const[n,setN]=useState(1);useEffect(()=>setN(1),[s.segment]);return <article className="seller-offer"><div><h3>{p.seller.name}</h3><span>{p.seller.country}{p.seller.verified?' · '+s.t('Проверенная плантация','Verified grower'):''}</span><p>{s.t('В наличии','Available')}: {available(p,s.segment)} {s.segment==='b2b'?s.t('коробок','boxes'):s.t('стеблей','stems')}</p></div><div><strong>{money(unitPrice(p,s.segment,s.currency),s.currency)}</strong><span> / {s.t('стебель','stem')}</span>{s.segment==='b2b'&&<p>{p.box_quantity} {s.t('стеблей в коробке','stems per box')}{p.wholesale?.ams_price&&<> · AMS {money(convert(Number(p.wholesale.ams_price),'RUB',s.currency),s.currency)}</>}</p>}<p>{s.t('Итого','Total')}: {money(itemPrice(p,s.segment,s.currency)*n,s.currency)}</p></div><div className="seller-offer-action">{!s.has(p.id)&&<Quantity value={n} max={available(p,s.segment)} onChange={setN}/>}<BuyButton p={p} n={n}/></div></article>}
